services:

  # ONOS controller
  onos:
    image: onosproject/onos:latest
    container_name: onos
    hostname: onos
    privileged: true
    networks:
      default:
      onos-net:
        ipv4_address: 172.20.0.100
    environment:
      - ONOS_APPS=drivers,fpm,gui,openflow
    ports:
      - "2620:2620"
      - "6653:6653"  # OpenFlow
      - "8101:8101"  # ONOS CLI
      - "8181:8181"  # ONOS Web UI
    tty: true
    stdin_open: true

  # FRR BGP speaker (AS65000)
  bgp-speaker:
    image: frrouting/frr-debian
    container_name: bgp-speaker
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    command:
      - /bin/sh
      - -c
      - |
        apt-get update && apt-get install -y iptables
        iptables -P FORWARD ACCEPT
        /usr/lib/frr/docker-start
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/AS65000/frr.conf:/etc/frr/frr.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # routers (AS65010)
  r65010:
    image: frrouting/frr-debian
    container_name: r65010
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/AS65010/frr.conf:/etc/frr/frr.conf
    networks:
      as65010:
        ipv4_address: 10.0.0.2
      R1R2br:
        ipv4_address: 172.19.0.2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # routers (AS65020)
  r65020:
    image: frrouting/frr-debian
    container_name: r65020
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/AS65020/frr.conf:/etc/frr/frr.conf
    networks:
      as65020:
        ipv4_address: 10.1.0.2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # routers (AS65021)
  r65021:
    image: frrouting/frr-debian
    container_name: r65021
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/AS65021/frr.conf:/etc/frr/frr.conf
    networks:
      as65021:
        ipv4_address: 10.2.0.2
      R1R2br:
        ipv4_address: 172.19.0.3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # web containers (AS65000)
  web65000:
    image: traefik/whoami
    container_name: web65000
    cap_add:
      - NET_ADMIN
    command:
      - |
        ip route del default
        ip route add default via 192.168.0.2
        sleep infinity

  # web containers (AS65010)
  web65010:
    image: traefik/whoami
    container_name: web65010
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      as65010:
        ipv4_address: 10.0.0.3
    command:
    - |
      ip route del default
      ip route add default via 10.0.0.2
      sleep infinity

  # web containers (AS65020)
  web65020:
    image: traefik/whoami
    container_name: web65020
    networks:
      as65020:
        ipv4_address: 10.1.0.3

  # web containers (AS65021)
  web65021:
    image: traefik/whoami
    container_name: web65021
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      as65021:
        ipv4_address: 10.2.0.3
    command:
    - |
      ip route del default
      ip route add default via 10.2.0.2
      sleep infinity

networks:
  as65000:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
  as65010:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  as65020:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
  as65021:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
  R1R2br:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
  onos-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
